# Generated by Django 5.0.6 on 2024-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('api_key', models.CharField(default='ff471cfd-49cc-44d3-a3e7-7e066b5dde06', max_length=255, unique=True)),
            ],
        ),
    ]
