# Generated by Django 5.0.6 on 2024-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='full_images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='short_images/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='71f90f58-7597-4a5a-a5ce-34a0fab04594', max_length=255, unique=True),
        ),
    ]
