# Generated by Django 5.0.6 on 2024-08-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_img_1_user_img_2_alter_company_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_2',
        ),
        migrations.AddField(
            model_name='user',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/full/'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/short/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='05723848-3514-4794-ba37-2dad3e07011e', max_length=255, unique=True),
        ),
    ]
