# Generated by Django 5.0.6 on 2024-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_img_1_remove_user_img_2_user_full_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='226feba3-7025-481e-b7ed-a5759e09ae19', max_length=255, unique=True),
        ),
    ]
