# Generated by Django 5.0.6 on 2024-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_company_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_image',
        ),
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='fda7ae66-601b-4653-94e0-7ac0daedb39e', max_length=255, unique=True),
        ),
    ]
