# Generated by Django 5.0.6 on 2024-08-12 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_full_image_remove_user_short_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='7f1dba8a-82d9-4625-9ab3-b96820e8b4a7', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CustomerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(upload_to='full_images/', verbose_name='Image 1')),
                ('img_2', models.ImageField(upload_to='short_images/', verbose_name='Image 2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
