# Generated by Django 5.0.6 on 2024-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_company_api_key_customerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='8f137079-b476-4002-8b9a-b88ef19a36a4', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customerimages',
            name='img_1',
            field=models.ImageField(upload_to='full_images/'),
        ),
        migrations.AlterField(
            model_name='customerimages',
            name='img_2',
            field=models.ImageField(upload_to='short_images/'),
        ),
        migrations.AlterField(
            model_name='customerimages',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
