# Generated by Django 5.0.6 on 2024-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_company_api_key_alter_customerimages_img_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerImages',
        ),
        migrations.AlterField(
            model_name='company',
            name='api_key',
            field=models.CharField(default='96e8430d-8b28-46a5-bcd6-b37ca031e70a', max_length=255, unique=True),
        ),
    ]
